### ISSUE TITLE
KEY_HDMI1, KEY_HDMI2, KEY_HDMI3 & KEY_HDMI4 don't work

### ISSUE THREAD

**Issue by saschaeggi** [jaruba/ha-samsungtv-custom#4]
The HDMI Keys don't work except KEY_HDMI which just cycle through the active HDMI Inputs.

**Comment by jaruba** [comment]
Yes, I know. I've tested all the available alternative samsung tv components also, those keys don't work in any of them.

Be sure that the "KEY_HDMI1", etc. codes are sent correctly to the TV, but they are not recognised by the TV as valid codes. I've searched high and low for any source I could find anywhere regarding Samsung TV key codes, they are not publicly released.

This is actually one of the main reasons I worked on this component, because I couldn't change the source with a key.. so I implemented key chaining!

This is how I change the sources to TV, Chromecast and PC:

2017 TV:
```
    source_list: '{"TV":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_ENTER","Manual":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER","Chromecast":"KEY_SOURCE+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_ENTER"}'
```

2019 TV:
```
    source_list: '{"TV":"KEY_SOURCE+KEY_DOWN+KEY_UP+KEY_LEFT+KEY_LEFT+KEY_ENTER","Manual":"KEY_SOURCE+KEY_DOWN+KEY_UP+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_ENTER","Chromecast":"KEY_SOURCE+KEY_DOWN+KEY_UP+KEY_LEFT+KEY_LEFT+KEY_RIGHT+KEY_RIGHT+KEY_ENTER"}'
```

**Comment by jaruba** [comment]
"PC" is set as "Manual" in the `source_list` so it also works with Google Home / Assistant, that doesn't allow "PC" as a keyword, but does allow "Manual".

**Comment by jaruba** [comment]
@saschaeggi

Have you succeeded using key chaining to solve HDMI source selection?

If so, please close the issue. I should remove KEY_HDMI1, 2, etc from examples, I don't think any Tizen based TV supports those key calls.

**Comment by saschaeggi** [comment]
@jaruba looks like the chaining works.
+1 on removing the KEY_HDMI1, 2 etc. from the examples

**Comment by jaruba** [comment]
I've removed the keys from the examples in the Readme
